volumes:
 certs:
   driver: local
 esdata01:
   driver: local
 kibanadata:
   driver: local
 metricbeatdata01:
   driver: local
 filebeatdata01:
   driver: local
 logstashdata01:
   driver: local


networks:
 default:
   name: cluster${instance}-network
   external: false


services:
 setup${instance}:
   image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
   container_name: cluster${instance}-setup
   volumes:
     - /mnt/data/mesh/cluster${instance}/certs:/usr/share/elasticsearch/config/certs
   user: "0"
   command: >
     bash -c '
       if [ x${ELASTIC_PASSWORD} == x ]; then
         echo "Set the ELASTIC_PASSWORD environment variable in the .env file";
         exit 1;
       elif [ x${KIBANA_PASSWORD} == x ]; then
         echo "Set the KIBANA_PASSWORD environment variable in the .env file";
         exit 1;
       fi;
       if [ ! -f config/certs/ca.zip ]; then
         echo "Creating CA";
         bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip;
         unzip config/certs/ca.zip -d config/certs;
       fi;
       if [ ! -f config/certs/certs.zip ]; then
         echo "Creating certs";
         echo -ne \
         "instances:\n"\
         "  - name: es${instance}\n"\
         "    dns:\n"\
         "      - es${instance}\n"\
         "      - localhost\n"\
         "    ip:\n"\
         "      - 127.0.0.1\n"\
         "  - name: kibana${instance}\n"\
         "    dns:\n"\
         "      - kibana${instance}\n"\
         "      - localhost\n"\
         "    ip:\n"\
         "      - 127.0.0.1\n"\
         > config/certs/instances.yml;
         bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in config/certs/instances.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key;
         unzip config/certs/certs.zip -d config/certs;
       fi;
       echo "Setting file permissions"
       chown -R root:root config/certs;
       find . -type d -exec chmod 750 \{\} \;;
       find . -type f -exec chmod 640 \{\} \;;
       echo "Waiting for Elasticsearch availability";
       until curl -s --cacert config/certs/ca/ca.crt https://es${instance}:9200 | grep -q "missing authentication credentials"; do sleep 30; done;
       echo "Setting kibana_system password";
       until curl -s -X POST --cacert config/certs/ca/ca.crt -u "elastic:${ELASTIC_PASSWORD}" -H "Content-Type: application/json" https://es${instance}:9200/_security/user/kibana_system/_password -d "{\"password\":\"${KIBANA_PASSWORD}\"}" | grep -q "^{}"; do sleep 10; done;
       echo "All done!";
     '
   healthcheck:
     test: ["CMD-SHELL", "[ -f config/certs/es${instance}/es${instance}.crt ]"]
     interval: 1s
     timeout: 5s
     retries: 20

 es${instance}:
   depends_on:
     setup${instance}:
       condition: service_healthy
   image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
   container_name: cluster${instance}-elastic
   labels:
     co.elastic.logs/module: elasticsearch
   user: "110"
   volumes:
     - /mnt/data/mesh/cluster${instance}/certs:/usr/share/elasticsearch/config/certs
     - /mnt/data/mesh/cluster${instance}/elastic:/usr/share/elasticsearch/data
     - /mnt/data/mesh/cluster${instance}/elastic/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
   ports:
     - 92${instance}:9200
     - 94${instance}:9443
   environment:
     - node.name=es${instance}
     - cluster.name=mesh-cluster-${instance}
     - discovery.type=single-node
     - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
     - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
     - bootstrap.memory_lock=true
     - xpack.security.enabled=true
     - xpack.security.http.ssl.enabled=true
     - xpack.security.http.ssl.key=certs/es${instance}/es${instance}.key
     - xpack.security.http.ssl.certificate=certs/es${instance}/es${instance}.crt
     - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
     - xpack.security.remote_cluster_server.ssl.key=certs/es${instance}/es${instance}.key
     - xpack.security.remote_cluster_server.ssl.certificate=certs/es${instance}/es${instance}.crt
     - xpack.security.transport.ssl.enabled=true
     - xpack.security.transport.ssl.key=certs/es${instance}/es${instance}.key
     - xpack.security.transport.ssl.certificate=certs/es${instance}/es${instance}.crt
     - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
     - xpack.security.transport.ssl.verification_mode=certificate
     - xpack.license.self_generated.type=trial
     - http.port=9200
     - remote_cluster.host="0.0.0.0"
     - remote_cluster.port=9443
     - xpack.security.remote_cluster_server.ssl.enabled=true
   ulimits:
     memlock:
       soft: -1
       hard: -1
   healthcheck:
     test:
       [
         "CMD-SHELL",
         "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
       ]
     interval: 10s
     timeout: 10s
     retries: 20

 kibana${instance}:
   depends_on:
     es${instance}:
       condition: service_healthy
   image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
   container_name: cluster${instance}-kibana
   labels:
     co.elastic.logs/module: kibana
   volumes:
     - /mnt/data/mesh/cluster${instance}/certs:/usr/share/kibana/config/certs
     - /mnt/data/mesh/cluster${instance}/kibana:/usr/share/kibana/data
     - /mnt/data/mesh/cluster${instance}/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
   user: "110"
   ports:
     - 56${instance}:5601
   environment:
     - SERVERNAME=kibana${instance}
     - ELASTICSEARCH_HOSTS=https://es${instance}:9200
     - ELASTICSEARCH_USERNAME=kibana_system
     - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
     - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
     - XPACK_SECURITY_ENCRYPTIONKEY=${ENCRYPTION_KEY}
     - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=${ENCRYPTION_KEY}
     - XPACK_REPORTING_ENCRYPTIONKEY=${ENCRYPTION_KEY}
     - SERVER_PORT=5601
#   mem_limit: ${KB_MEM_LIMIT}
   healthcheck:
     test:
       [
         "CMD-SHELL",
         "curl -s -I http://localhost:5601/cluster${instance} | grep -q 'HTTP/1.1 302 Found'",
       ]
     interval: 10s
     timeout: 10s
     retries: 20